### ISSUE TITLE
This is not working

### ISSUE THREAD

**Issue by saileshkush95** [CleitonDeLima/django-tawkto#4]
I treid it but this is not working. Please help me out
![DeepinScreenshot_select-area_20190329191959](https://user-images.githubusercontent.com/28560875/55236262-ac6d7e00-5257-11e9-9003-8c1bd928d9a6.png)
Where to include above code. in base.html or somewhere else
Please provide better gudie
I'm trying to include this package in this websites
http://sandeepkush.herokuapp.com/

It only works when i open new windows for chat

**Comment by CleitonDeLima** [comment]
if you want the chat to appear on every page, this script goes in the base.html.
