### ISSUE TITLE
Can't use multiple chat widget in a single web app

### ISSUE THREAD

**Issue by sikander27** [CleitonDeLima/django-tawkto#6]
I have tried to use the django-tawko, but I wanted to use more than one tawk.to widget. But how can I do that since we have only one tawk.to id variable in settings.

**Comment by CleitonDeLima** [comment]
Hi @sikander27 

Using it that way doesn't work?

`{% tawkto_script widget_id='somewidgetid' %}`

**Comment by sikander27** [comment]
> Hi @sikander27
> 
> Using it that way doesn't work?
> 
> `{% tawkto_script widget_id='somewidgetid' %}`

Actually, I want to use multiple properties i.e. One widget for the home page, one for the customer support and so on. So each widget will have separate dashboard and customer support people

**Comment by sikander27** [comment]
> Hi @sikander27
> 
> Using it that way doesn't work?
> 
> `{% tawkto_script widget_id='somewidgetid' %}`

Is there any way to use it like {% tawkto_script TAWKTO_ID_SITE='propertyid' %}, where we provide tawk_id directly in the script?
Please help me with this. I think we can implement something like this if you could configure the package that way.
In a normal website, we would simply have pasted different script for different tawk.to chat. So in Django too, we should have an option to use different property on the same site.

**Comment by CleitonDeLima** [comment]
> Is there any way to use it like {% tawkto_script TAWKTO_ID_SITE='propertyid' %}, where we provide tawk_id directly in the script?
> Please help me with this. I think we can implement something like this if you could configure the package that way.
> In a normal website, we would simply have pasted different script for different tawk.to chat. So in Django too, we should have an option to use different property on the same site.

Hi,

Feel free to open a PR, the library is simple and open source (I think it was my first project). In 20min you can make your customization with the django `include` if you think it is necessary for your project. :)

**Comment by sikander27** [comment]
> > Is there any way to use it like {% tawkto_script TAWKTO_ID_SITE='propertyid' %}, where we provide tawk_id directly in the script?
> > Please help me with this. I think we can implement something like this if you could configure the package that way.
> > In a normal website, we would simply have pasted different script for different tawk.to chat. So in Django too, we should have an option to use different property on the same site.
> 
> Hi,
> 
> Feel free to open a PR, the library is simple and open source (I think it was my first project). In 20min you can make your customization with the django `include` if you think it is necessary for your project. :)

Hi,

Thanks for letting me know about it. I have created a PR, please merge it with your project.

**Comment by CleitonDeLima** [comment]
Thank @sikander27  for contributing :wink: 

Updated!
