### ISSUE TITLE
Not supported with django 3.1.2

### ISSUE THREAD

**Issue by sikander27** [CleitonDeLima/django-tawkto#7]
I tried using this package with django 3.1.2 but it wasn't working. So I tried to use an older version 3.0.11 and it works.

**Comment by CleitonDeLima** [comment]
Hi @sikander27  
What error happens in this version?

**Comment by sikander27** [comment]
> Hi @sikander27  
> What error happens in this version?

Basically it was not rendering, when I inspected the page I could see the tawk.to script as well as tawk.to html code. But the style was set to none. I changed it to block just to test it but apparently the chat was not working

**Comment by CleitonDeLima** [comment]
Looks here:

https://docs.djangoproject.com/en/3.1/ref/settings/#secure-referrer-policy

**Comment by sikander27** [comment]
> Looks here:
> 
> https://docs.djangoproject.com/en/3.1/ref/settings/#secure-referrer-policy

Should I set to it to unsafe-url like SECURE_REFERRER_POLICY = unsafe-url .
If not what should be the value of it.
Thanks for your response.

**Comment by CleitonDeLima** [comment]
In my project I had to configure `SECURE_REFERRER_POLICY=None`
I didn't go very deep but that's it.

**Comment by sikander27** [comment]
okay thanks
